### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'units'

### ISSUE THREAD

**Issue by Jovonni** [jacobgil/keras-dcgan#28]
python dcgan.py --mode train --batch_size <num>

I am loading the mnist dataset from a local pickle file, and this error is occuring. Debugging now, and will update as I learn more

---------

more

//anaconda/envs/py35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
//anaconda/envs/py35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
//anaconda/envs/py35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
//anaconda/envs/py35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "DCGAN.py", line 167, in <module>
    train(BATCH_SIZE=args.batch_size)
  File "DCGAN.py", line 91, in train
    g = generator_model()
  File "DCGAN.py", line 22, in generator_model
    model.add(Dense(input_dim=100, output_dim=1024))

---------------

 could it be my TF version? It shouldn't be...

**Comment by Jovonni** [comment]
Fixed
